const $=id=>document.getElementById(id),text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
const fields=[['first_name','First name',50],['last_name','Last name',50],['organization','Company / organization',150],['job_title','Job title / role',100],['city','City',100],['region','State / province',100],['country','Country',100],['phone','Phone',40],['designation','Professional designation',100],['license_number','License number',80],['license_region','License jurisdiction',100]];
async function api(path,data){const r=await fetch('/api'+path,{credentials:'same-origin',...(data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})});const j=await r.json();if(r.status===401){location.replace('/LMS/?login=1&next=account');throw Error('Please sign in.');}if(!r.ok)throw Error(j.error||'Unable to load account.');return j;}
const message=(s,error=false)=>{$('account-message').textContent=s;$('account-message').classList.toggle('error',error);};
async function load(){const [d,me,paid]=await Promise.all([api('/account'),api('/me'),api('/receipts')]);$('account-content').hidden=false;$('account-email').textContent='Sign-in email: '+d.user.email;$('profile-fields').replaceChildren();for(const [key,label,max] of fields){const wrap=document.createElement('div'),lab=text('label',label),input=document.createElement('input');input.id='profile-'+key;lab.htmlFor=input.id;input.maxLength=max;input.required=['first_name','last_name','country'].includes(key);input.value=d.profile[key];wrap.append(lab,input);$('profile-fields').append(wrap);}$('profile-updates').checked=d.profile.marketing_opt_in;
 $('access-summary').textContent=d.access.libraryActive?'Active · One-year video library access':d.access.grants.some(g=>g.status==='active')?'Active · Selected course access':'No active paid-course access';$('access-grants').replaceChildren();for(const g of d.access.grants){$('access-grants').append(text('p',`${g.course_id?g.course_code+' · '+g.title:'Entire video library'} — ${g.status}${g.expires_at?' · expires '+new Date(g.expires_at*1000).toLocaleDateString():' · expiration not set'}`));}if(!d.access.grants.length)$('access-grants').append(text('p','You can browse free resources now. Enroll or redeem an instructor coupon to unlock videos.'));
 $('account-learning').replaceChildren();if(!d.learning.length)$('account-learning').append(text('p','You have not started a course yet.'));for(const c of d.learning){const row=text('p',`${c.course_code} · ${c.title} — ${c.completed_at?'Completed':Math.min(100,Math.floor(c.watched_seconds/c.duration_seconds*100)||0)+'% watched'} `);if(c.published&&!c.deleted_at){const a=text('a','Open course');a.href='/LMS/?course='+encodeURIComponent(c.id);row.append(a);}else row.append(text('span','(Not currently available)'));$('account-learning').append(row);}
 $('account-receipts').replaceChildren();if(!paid.receipts.length)$('account-receipts').append(text('p','Receipts for library purchases appear here. Coupon access has no charge, so it has no receipt.'));for(const r of paid.receipts){const p=text('p',`${new Date(r.paidAt*1000).toLocaleDateString()} · ${r.item} · ${new Intl.NumberFormat(undefined,{style:'currency',currency:r.currency}).format(Number(r.amount))} · ${r.number} `),a=text('a','View / print receipt');a.href='/LMS/receipt.html?id='+encodeURIComponent(r.id);p.append(a);$('account-receipts').append(p);}
 $('account-certificates').replaceChildren();if(!d.certificates.length)$('account-certificates').append(text('p','Certificates appear here after you pass a course test.'));for(const c of d.certificates){const p=document.createElement('p'),a=text('a',c.course_title+' — '+c.learner_name);a.href='/LMS/certificate.html?id='+encodeURIComponent(c.id);p.append(a);$('account-certificates').append(p);}message('Your account is ready.');}
$('profile-form').onsubmit=async e=>{e.preventDefault();$('profile-save').disabled=true;try{const data=Object.fromEntries(fields.map(([key])=>[key,$('profile-'+key).value]));data.marketing_opt_in=$('profile-updates').checked;await api('/account',data);message('Profile saved. Your updated name will be used on future certificates.');}catch(e){message(e.message,true);}finally{$('profile-save').disabled=false;}};
load().catch(e=>message(e.message,true));
