import {Unzip,UnzipInflate} from 'fflate';
import Quill from 'quill';
const $=id=>document.getElementById(id),el=(tag,value)=>{const n=document.createElement(tag);n.textContent=value;return n;};
let current=null,courseData=null,preview=null,busy=false,adminCourses=[],deleteTarget=null;
const quill=new Quill('#article-body',{theme:'snow',placeholder:'Start writing your article. Use headings to organize ideas, short paragraphs for readability, and lists for steps or takeaways.',modules:{toolbar:'#article-toolbar',history:{delay:1200,maxStack:100,userOnly:true}},formats:['header','bold','italic','underline','strike','blockquote','list','link','indent']});
const articleTags=new Set(['P','H2','H3','UL','OL','LI','BLOCKQUOTE','STRONG','B','EM','I','U','S','A','BR','HR']);
function cleanArticleHtml(html){const doc=new DOMParser().parseFromString(String(html||''),'text/html');function clean(node){return [...node.childNodes].map(child=>{if(child.nodeType===Node.TEXT_NODE)return document.createTextNode(child.nodeValue);if(child.nodeType!==Node.ELEMENT_NODE)return document.createDocumentFragment();if(!articleTags.has(child.tagName)){const fragment=document.createDocumentFragment();for(const nested of [...child.childNodes])fragment.append(clean(nested));return fragment;}const out=document.createElement(child.tagName.toLowerCase());if(child.tagName==='A'){const href=child.getAttribute('href')||'';if(/^(https?:|mailto:)/i.test(href)){out.href=href;if(/^https?:/i.test(href)){out.target='_blank';out.rel='noopener noreferrer';}}}for(const nested of [...child.childNodes])out.append(clean(nested));return out;});}const result=document.createElement('div');for(const child of [...doc.body.childNodes])result.append(clean(child));return result.innerHTML;}
function articleContent(value){if(/<\/?[a-z][\s\S]*>/i.test(value||''))return cleanArticleHtml(value);return String(value||'').split(/\n\s*\n/).map(p=>`<p>${p.split('\n').map(line=>{const n=document.createElement('span');n.textContent=line;return n.innerHTML;}).join('<br>')}</p>`).join('');}
function renderArticlePreview(){const preview=$('article-preview'),title=el('h1',$('course-name').value.trim()||'Article title');title.className='article-preview-title';preview.replaceChildren(title);const body=document.createElement('div');body.innerHTML=cleanArticleHtml(quill.getSemanticHTML());preview.append(body);}
const msg=(s,error=false)=>{$('admin-message').textContent=s;$('admin-message').classList.toggle('error',error);};
async function api(path,data){const r=await fetch('/api/admin'+path,{credentials:'same-origin',...(data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})});const j=await r.json().catch(()=>({error:'Unexpected response.'}));if(!r.ok)throw Error(j.error||'Request failed.');return j;}
async function binary(path,bytes){for(let n=0;n<3;n++){try{const r=await fetch('/api/admin'+path,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/octet-stream'},body:bytes});if(r.ok)return;if(r.status<500)throw Object.assign(Error((await r.json()).error),{permanent:true});throw Error('Upload interrupted.');}catch(e){if(e.permanent||n===2)throw e;}}}
function section(id){for(const x of ['admin-courses','course-editor','admin-learners','admin-coupons','admin-notes','activity-preview','course-delete-panel'])$(x).hidden=x!==id;}
async function task(fn){if(busy)return;busy=true;const buttons=[...document.querySelectorAll('button')];const states=buttons.map(b=>b.disabled);buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){msg(e.message,true);}finally{busy=false;buttons.forEach((b,i)=>b.disabled=states[i]);}}
async function list(){const r=await api('/courses');adminCourses=r.courses;$('category-options').replaceChildren(...[...new Set(r.courses.map(c=>c.category))].map(c=>new Option(c)));drawCourses();section('admin-courses');msg('Manage courses, uploads, tests and activities.');}
function drawCourses(){const q=$('admin-course-search').value.trim().toLowerCase(),filter=$('admin-course-filter').value;const visible=adminCourses.filter(c=>(filter==='trash'?!!c.deleted_at:!c.deleted_at&&(filter==='active'||(filter==='published'?c.published:!c.published)))&&(!q||(c.title+' '+c.course_code+' '+c.category).toLowerCase().includes(q)));$('admin-course-summary').textContent=`${adminCourses.filter(c=>!c.deleted_at&&c.published).length} published · ${adminCourses.filter(c=>!c.deleted_at&&!c.published).length} drafts · ${adminCourses.filter(c=>c.deleted_at).length} in Trash`;$('course-list').replaceChildren();if(!visible.length)$('course-list').append(el('p','No learning items match this filter.'));for(const c of visible){const row=el('article','');row.className='admin-row';const info=el('div','');info.append(el('h3',c.course_code+' · '+c.title),el('p',`${c.category} · ${c.content_type|| (c.topic_path?'guide':'course')} · ${c.access_tier==='free'?'Free':'Course Pack'} · ${c.deleted_at?'In Trash':c.published?'Published':'Draft'} · ${c.youtube_id?'YouTube':c.asset_key?'Uploaded video':'No video'}`));row.append(info);if(c.deleted_at){const restore=el('button','Restore as draft');restore.onclick=()=>task(async()=>{await api('/courses/'+c.id+'/restore',{revision:c.admin_revision,confirmCode:c.course_code});await list();msg('Restored as a draft.');});row.append(restore);}else{const b=el('button','View / edit');b.onclick=()=>task(()=>edit(c.id));row.append(b);const trash=el('button','Delete');trash.className='secondary';trash.onclick=()=>{deleteTarget=c;$('delete-course-code').value='';section('course-delete-panel');msg('Confirm deletion of '+c.course_code+' · '+c.title);};row.append(trash);}$('course-list').append(row);}}
$('admin-course-search').oninput=drawCourses;$('admin-course-filter').onchange=drawCourses;
$('course-delete-form').onsubmit=e=>{e.preventDefault();task(async()=>{await api('/courses/'+deleteTarget.id+'/trash',{revision:deleteTarget.admin_revision,confirmCode:$('delete-course-code').value.trim()});deleteTarget=null;await list();msg('Course moved to Trash. Learner history and uploaded files were preserved.');});};
$('cancel-course-delete').onclick=()=>{deleteTarget=null;section('admin-courses');msg('Deletion canceled.');};
function field(label,value,tag='input'){const wrap=el('label',label);const input=document.createElement(tag);input.value=value;wrap.append(input);return {wrap,input};}
function questions(q=[]){$('quiz-editor').replaceChildren();for(let i=0;i<10;i++){const item=el('fieldset','');item.className='quiz-item';item.append(el('legend',`Question ${i+1}`));const prompt=field('Question',q[i]?.prompt||'','textarea');prompt.input.rows=2;prompt.input.maxLength=1500;prompt.input.dataset.prompt='true';item.append(prompt.wrap);const opts=q[i]?.options||['','',''];const choices=field('Options — one per line',opts.join('\n'),'textarea');choices.input.rows=Math.max(3,opts.length);choices.input.dataset.options='true';item.append(choices.wrap);const correct=field('Correct option number (1–6)',String((q[i]?.correct||0)+1));correct.input.type='number';correct.input.min=1;correct.input.max=6;correct.input.dataset.correct='true';item.append(correct.wrap);$('quiz-editor').append(item);}}
async function edit(id){current=id;courseData=id?await api('/courses/'+id):null;const c=courseData?.course||{};for(const [dom,key] of [['course-code','course_code'],['course-category','category'],['course-name','title'],['course-description','description'],['course-level','level']])$(dom).value=c[key]|| (key==='level'?'Foundational':'');$('course-slug').value=c.slug||c.topic_path?.split('/').filter(Boolean).pop()||'';$('content-type').value=c.content_type||(c.topic_path?'guide':'course');$('access-tier').value=c.access_tier|| (c.topic_path?'free':'course_pack');$('course-published').checked=!!c.published;$('editor-heading').textContent=id?'Edit '+c.course_code:'New learning item';questions(courseData?.questions);$('save-quiz').checked=!!courseData?.questions?.length;$('quiz-details').hidden=false;$('course-assets').hidden=!id;$('admin-take-course').hidden=!(id&&c.published&&(c.asset_key||c.youtube_id)&&c.duration_seconds>0);$('youtube-url').value=c.youtube_id?'https://www.youtube.com/watch?v='+c.youtube_id:'';$('youtube-duration').value=c.duration_seconds||'';$('video-progress-mode').value=(c.asset_key||c.youtube_id)?'':'reset';$('video-summary').textContent=c.youtube_id?`YouTube video · ${c.duration_seconds} seconds`:c.asset_key?`Video uploaded · ${Math.ceil(c.duration_seconds/60)} minutes`:'No video uploaded yet.';$('video-form').hidden=false;$('video-file').value='';$('activity-file').value='';$('activity-title').value='';quill.setText('');quill.clipboard.dangerouslyPasteHTML(articleContent(courseData?.modules?.find(m=>m.module_type==='article')?.body||''));$('article-preview').hidden=true;$('article-body').hidden=false;$('article-preview-toggle').textContent='Preview';$('article-preview-toggle').setAttribute('aria-pressed','false');for(const m of ['video','article','lumi','test']){const v=courseData?.modules?.find(x=>x.module_type===m);$('module-'+m).checked=!!v?.enabled;$('module-'+m+'-published').checked=!!v?.published;}drawCaptions();drawActivities();section('course-editor');msg(id?'Edit any learning format, access setting, and module below.':'Create the item, select its modules, and save before adding uploaded assets.');}
$('admin-take-course').onclick=()=>{if(current)location.href='/LMS/?course='+encodeURIComponent(current)+'&adminPreview='+encodeURIComponent(current);};
function drawActivities(){const box=$('activity-list');box.replaceChildren();for(const a of courseData?.activities||[]){const row=el('div','');row.className='activity-item';row.append(el('h3',a.title),el('p',`${a.main_library||'Uploading'} · ${a.verified_at?'Completion tracking verified':'Not yet verified'}${a.attached?` · Attached (${a.required?'required':'optional'})`:''}`));if(a.status==='ready'){const previewButton=el('button','Preview & verify');previewButton.onclick=()=>task(async()=>{preview=await api('/activities/'+a.id+'/launch',{});$('preview-frame').src=preview.playerUrl;$('preview-status').textContent='Complete the entire activity to verify completion tracking.';section('activity-preview');});const optional=el('button','Attach as optional');optional.onclick=()=>task(async()=>{await api('/activities/'+a.id+'/attach',{required:false});await edit(current);msg('Activity attached as optional.');});const required=el('button','Require before test');required.disabled=!a.verified_at;required.onclick=()=>task(async()=>{await api('/activities/'+a.id+'/attach',{required:true});await edit(current);msg('Activity completion is now required before the test.');});row.append(previewButton,optional,required);}box.append(row);}}
$('course-form').onsubmit=e=>{e.preventDefault();task(async()=>{const d={title:$('course-name').value,description:$('course-description').value,category:$('course-category').value,course_code:$('course-code').value,level:$('course-level').value,published:$('course-published').checked,revision:courseData?.course.admin_revision,content_type:$('content-type').value,access_tier:$('access-tier').value,slug:$('course-slug').value,modules:['test','video','article','lumi'].map(type=>({type,enabled:$('module-'+type).checked,published:$('module-'+type+'-published').checked,body:type==='article'?cleanArticleHtml(quill.getSemanticHTML()):''}))};if($('save-quiz').checked&&$('module-test').checked)d.questions=[...$('quiz-editor').children].map(f=>({prompt:f.querySelector('[data-prompt]').value,options:f.querySelector('[data-options]').value.split('\n').map(x=>x.trim()).filter(Boolean),correct:Number(f.querySelector('[data-correct]').value)-1}));const r=await api(current?'/courses/'+current:'/courses',d);await edit(r.id);msg('Learning item and module settings saved.');});};
$('article-preview-toggle').onclick=()=>{const previewing=$('article-preview-toggle').getAttribute('aria-pressed')!=='true';if(previewing)renderArticlePreview();$('article-toolbar').hidden=previewing;$('article-body').hidden=previewing;$('article-preview').hidden=!previewing;$('article-preview-toggle').setAttribute('aria-pressed',String(previewing));$('article-preview-toggle').textContent=previewing?'Back to editor':'Preview';};
quill.on('text-change',()=>{if(!$('article-preview').hidden)renderArticlePreview();});$('course-name').addEventListener('input',()=>{if(!$('article-preview').hidden)renderArticlePreview();});
async function duration(file){const url=URL.createObjectURL(file),v=document.createElement('video');try{return await new Promise((resolve,reject)=>{v.onloadedmetadata=()=>resolve(v.duration);v.onerror=()=>reject(Error('Unable to read this MP4.'));v.src=url;});}finally{v.removeAttribute('src');v.load();URL.revokeObjectURL(url);}}
$('video-form').onsubmit=e=>{e.preventDefault();task(async()=>{const f=$('video-file').files[0];if(!f||!f.name.toLowerCase().endsWith('.mp4')||f.size>2*1024**3)throw Error('Choose an MP4 up to 2 GB.');const d=await duration(f),u=await api('/courses/'+current+'/video-upload',{size:f.size,duration:d,revision:courseData.course.admin_revision,progressMode:$('video-progress-mode').value});try{const count=Math.ceil(f.size/u.partSize);for(let n=1;n<=count;n++){msg(`Uploading video: part ${n} of ${count}. Keep this page open.`);await binary(`/video-uploads/${u.id}/part?number=${n}`,f.slice((n-1)*u.partSize,n*u.partSize));}await api('/video-uploads/'+u.id+'/complete',{});}catch(e){try{await api('/video-uploads/'+u.id+'/abort',{});}catch{}throw e;}await edit(current);msg('Video uploaded and linked to the course.');});};
$('youtube-form').onsubmit=e=>{e.preventDefault();task(async()=>{await api('/courses/'+current+'/youtube',{url:$('youtube-url').value,duration:Number($('youtube-duration').value),revision:courseData.course.admin_revision,progressMode:$('video-progress-mode').value});await edit(current);msg('YouTube link saved. Learners will watch it inside the course.');});};
async function unpack(file){if(!file||!file.name.toLowerCase().endsWith('.h5p')||file.size>60*1024**2)throw Error('Choose a Lumi .h5p export up to 60 MB.');const files=[],paths=new Set();let total=0,error;const unzip=new Unzip(f=>{if(f.name.endsWith('/'))return;if(paths.has(f.name)||files.length>=2000){error=Error('Duplicate paths or too many files.');return;}paths.add(f.name);const chunks=[];let size=0;const entry={path:f.name,bytes:null};files.push(entry);f.ondata=(err,chunk,final)=>{if(error)return;if(err){error=err;return;}size+=chunk.length;total+=chunk.length;if(size>16*1024**2||total>128*1024**2){error=Error('Expanded package exceeds the 16 MB/file or 128 MB total limit.');f.terminate?.();return;}chunks.push(chunk);if(final){entry.bytes=new Uint8Array(size);let pos=0;for(const c of chunks){entry.bytes.set(c,pos);pos+=c.length;}}};f.start();});unzip.register(UnzipInflate);const bytes=new Uint8Array(await file.arrayBuffer());for(let i=0;i<bytes.length;i+=65536){unzip.push(bytes.subarray(i,i+65536),i+65536>=bytes.length);if(error)throw error;}if(files.some(f=>!f.bytes))throw Error('Incomplete H5P archive.');return files;}
const hash=async bytes=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),x=>x.toString(16).padStart(2,'0')).join('');
$('activity-form').onsubmit=e=>{e.preventDefault();task(async()=>{msg('Validating and preparing the Lumi package…');const files=await unpack($('activity-file').files[0]),manifest=[];for(const f of files)manifest.push({path:f.path,size:f.bytes.length,sha256:await hash(f.bytes)});const p=await api('/courses/'+current+'/activities',{title:$('activity-title').value,files:manifest});for(let i=0;i<files.length;i++){msg(`Uploading Lumi activity: ${i+1} of ${files.length} files. Keep this page open.`);await binary('/activities/'+p.id+'/file?path='+encodeURIComponent(files[i].path),files[i].bytes);}await api('/activities/'+p.id+'/finalize',{});await edit(current);msg('Lumi activity uploaded. Preview and complete it to verify tracking, then attach it.');});};
window.addEventListener('message',async e=>{if(!preview||e.source!==$('preview-frame').contentWindow||e.origin!=='null'||e.data?.type!=='acpe-activity-complete'||e.data.token!==preview.token)return;try{await api('/activities/'+preview.activityId+'/verify',e.data);$('preview-status').textContent='Completion tracking verified. Close this preview, then attach the activity as optional or required.';}catch(err){$('preview-status').textContent=err.message;}});
$('close-preview').onclick=()=>task(async()=>{preview=null;$('preview-frame').removeAttribute('src');await edit(current);});
$('courses-tab').onclick=()=>task(list);$('editor-back').onclick=()=>task(list);$('new-course').onclick=()=>task(()=>edit(null));
$('notes-tab').onclick=()=>task(async()=>{$('build-notes').textContent=(await api('/notes')).text;section('admin-notes');msg('Private setup and build notes.');});
$('learners-tab').onclick=()=>task(async()=>{const r=await api('/learners');$('learners-list').replaceChildren();$('learner-results').hidden=true;for(const u of r.learners){const row=el('div','');row.className='admin-row';row.append(el('p',`${u.name} · ${u.email} · ${u.email_verified_at?'Email confirmed':'Email not confirmed'} · ${u.tests} submitted tests · ${u.certificates} certificates`));if(!u.email_verified_at){const v=el('button','Mark email confirmed');v.className='secondary';v.onclick=()=>task(async()=>{await api('/learners/'+u.id+'/verify-email',{});$('learners-tab').click();msg(u.email+' is now confirmed.');});row.append(v);}const b=el('button','View scores');b.onclick=()=>task(async()=>{const r=await api('/learners/'+u.id);$('learner-results').replaceChildren(el('h3',u.name));if(!r.results.length)$('learner-results').append(el('p','No submitted tests.'));for(const q of r.results)$('learner-results').append(el('p',`${q.course_code} · ${q.title} · Attempt ${q.attempt_number}: ${q.score}% (${q.passed?'Passed':'Not passed'})`));$('learner-results').hidden=false;});row.append(b);$('learners-list').append(row);}section('admin-learners');msg('Learner records are administrator-only.');});
$('admin-signout').onclick=()=>task(async()=>{await fetch('/api/auth/logout',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});location.href='/LMS/';});
window.addEventListener('beforeunload',e=>{if(busy){e.preventDefault();e.returnValue='';}});
task(async()=>{const r=await fetch('/api/me'),j=await r.json();if(!j.user?.admin)throw Error('Sign in with an authorized administrator account.');$('admin-content').hidden=false;$('admin-account').textContent=j.user.name;await list();});

function drawCaptions(){const c=courseData?.captions;$('captions-summary').textContent=!c||(!c.captions&&!c.transcript)?'No captions or transcript yet.':[c.captions?'Captions uploaded':'No captions',c.transcript?`transcript (${c.transcriptLength.toLocaleString()} characters)`:'no transcript'].join(' · ')+(c.updatedAt?` · updated ${new Date(c.updatedAt*1000).toLocaleDateString()}`:'');$('captions-remove').hidden=!c?.captions;$('transcript-remove').hidden=!c?.transcript;$('captions-file').value='';$('transcript-file').value='';}
$('captions-form').onsubmit=e=>{e.preventDefault();task(async()=>{const captions=$('captions-file').files[0],transcript=$('transcript-file').files[0];if(!captions&&!transcript)throw Error('Choose a caption file, a transcript file, or both.');const d={};if(captions)d.captions=await captions.text();if(transcript)d.transcript=await transcript.text();await api('/courses/'+current+'/captions',d);await edit(current);$('admin-captions-section').scrollIntoView({block:'start'});msg('Captions and transcript saved.');});};
for(const [id,field,label] of [['captions-remove','captions','Captions'],['transcript-remove','transcript','Transcript']])$(id).onclick=()=>task(async()=>{if(!confirm(`Remove the ${label.toLowerCase()} from this course?`))return;await api('/courses/'+current+'/captions',{[field]:null});await edit(current);msg(label+' removed.');});
const day=s=>new Date(s*1000).toLocaleDateString();
const endOfDay=value=>value?Math.floor(new Date(value+'T23:59:59').getTime()/1000):null;
const dateInput=s=>{if(!s)return '';const d=new Date(s*1000);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
function couponStatus(c){if(c.disabled_at)return 'Disabled';if(c.expires_at&&c.expires_at<=Date.now()/1000)return 'Ended';if(c.max_redemptions&&c.redemptions>=c.max_redemptions)return 'Limit reached';return 'Active';}
async function coupons(){const r=await api('/coupons');$('coupon-list').replaceChildren();$('coupon-redemptions').hidden=true;if(!r.coupons.length)$('coupon-list').append(el('p','No coupon codes yet.'));for(const c of r.coupons){const row=el('article','');row.className='admin-row';const info=el('div','');const code=el('h3',c.code);code.className='coupon-code';info.append(code,el('p',[c.label,`${couponStatus(c)}`,`Used ${c.redemptions}${c.max_redemptions?' of '+c.max_redemptions:''}`,`${c.access_days} days of access`,c.expires_at?'Redeem by '+day(c.expires_at):'No end date'].filter(Boolean).join(' · ')));row.append(info);const actions=el('div','');actions.className='coupon-actions';
 const copy=el('button','Copy code');copy.className='secondary';copy.onclick=async()=>{try{await navigator.clipboard.writeText(c.code);msg('Copied '+c.code+'.');}catch{msg('Copy failed. Select the code and copy it manually.',true);}};
 const who=el('button','Who used it');who.className='secondary';who.onclick=()=>task(async()=>{const list=(await api('/coupons/'+c.id+'/redemptions')).redemptions;$('coupon-redemptions').replaceChildren(el('h3',c.code+' · '+list.length+' redemption'+(list.length===1?'':'s')));if(!list.length)$('coupon-redemptions').append(el('p','Nobody has used this code yet.'));for(const x of list)$('coupon-redemptions').append(el('p',`${x.name} · ${x.email} · redeemed ${day(x.redeemed_at)} · ${x.revoked_at?'access revoked':x.expires_at?'access until '+day(x.expires_at):'access active'}`));$('coupon-redemptions').hidden=false;$('coupon-redemptions').scrollIntoView({block:'nearest'});});
 const save=(changes,done)=>task(async()=>{await api('/coupons/'+c.id,{label:c.label,maxRedemptions:c.max_redemptions,expiresAt:c.expires_at,disabled:!!c.disabled_at,...changes});await coupons();msg(done);});
 const toggle=el('button',c.disabled_at?'Enable':'Disable');toggle.className='secondary';toggle.onclick=()=>save({disabled:!c.disabled_at},c.code+(c.disabled_at?' enabled.':' disabled. Learners who already redeemed it keep their access.'));
 const editButton=el('button','Edit');editButton.className='secondary';editButton.onclick=()=>{const form=document.createElement('form');form.className='coupon-edit profile-grid';const fields={};for(const [key,label,type,value] of [['label','Label','text',c.label],['max','Use limit (blank = unlimited)','number',c.max_redemptions??''],['expires','Last day to redeem (blank = none)','date',dateInput(c.expires_at)]]){const wrap=el('div',''),lab=el('label',label),input=document.createElement('input');input.type=type;input.value=value;input.id='coupon-'+c.id+'-'+key;lab.htmlFor=input.id;if(type==='number')input.min=1;wrap.append(lab,input);fields[key]=input;form.append(wrap);}const submit=el('button','Save changes');form.append(submit);form.onsubmit=e=>{e.preventDefault();const expires=fields.expires.value===dateInput(c.expires_at)?c.expires_at:endOfDay(fields.expires.value);save({label:fields.label.value,maxRedemptions:fields.max.value?Number(fields.max.value):null,expiresAt:expires},c.code+' updated.');};editButton.disabled=true;row.append(form);fields.label.focus();};
 actions.append(copy,who,editButton,toggle);row.append(actions);$('coupon-list').append(row);}
 section('admin-coupons');msg('Create and manage coupon codes.');}
$('coupons-tab').onclick=()=>task(coupons);
$('coupon-create').onsubmit=e=>{e.preventDefault();task(async()=>{const r=await api('/coupons',{code:$('coupon-new-code').value,label:$('coupon-new-label').value,accessDays:Number($('coupon-new-days').value),maxRedemptions:$('coupon-new-max').value?Number($('coupon-new-max').value):null,expiresAt:endOfDay($('coupon-new-expires').value)});for(const id of ['coupon-new-code','coupon-new-label','coupon-new-max','coupon-new-expires'])$(id).value='';$('coupon-new-days').value=365;await coupons();msg('Created code '+r.code+'.');});};
