-- Generated from MP4 headers. Zero hours means credits are not yet assigned.
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-4','Course 4','On-demand video course.','General','Not specified',0,'courses/course-4.mp4',1,1636.316462585034) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-5','Course 5','On-demand video course.','General','Not specified',0,'courses/course-5.mp4',1,1712.635918367347) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-6','Course 6','On-demand video course.','General','Not specified',0,'courses/course-6.mp4',1,1670.6915192743763) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-7','Course 7','On-demand video course.','General','Not specified',0,'courses/course-7.mp4',1,1674.985918367347) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-8','Course 8','On-demand video course.','General','Not specified',0,'courses/course-8.mp4',1,1670.140566893424) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-9','Course 9','On-demand video course.','General','Not specified',0,'courses/course-9.mp4',1,1664.9187981859411) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-10','Course 10','On-demand video course.','General','Not specified',0,'courses/course-10.mp4',1,1683.437097505669) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-11','Course 11','On-demand video course.','General','Not specified',0,'courses/course-11.mp4',1,1697.1573111573111) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-12','Course 12','On-demand video course.','General','Not specified',0,'courses/course-12.mp4',1,1625.7880725623584) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-13','Course 13','On-demand video course.','General','Not specified',0,'courses/course-13.mp4',1,1670.052267573696) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-14','Course 14','On-demand video course.','General','Not specified',0,'courses/course-14.mp4',1,1633.6742630385488) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-15','Course 15','On-demand video course.','General','Not specified',0,'courses/course-15.mp4',1,1760.0343764172335) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
INSERT INTO courses (id,title,description,category,level,hours,asset_key,published,duration_seconds) VALUES ('course-16','Course 16','On-demand video course.','General','Not specified',0,'courses/course-16.mp4',1,1765.2743764172335) ON CONFLICT(id) DO UPDATE SET asset_key=excluded.asset_key,duration_seconds=excluded.duration_seconds;
