import {youtubeId,checkVideoChange,videoChangeStatements} from './video-source.js';
const json=(v,status=200,headers={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store',...headers}});
const fail=(status,message)=>{throw Object.assign(Error(message),{status});};
const uuid=()=>crypto.randomUUID();
const sha=async v=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',typeof v==='string'?new TextEncoder().encode(v):v)),n=>n.toString(16).padStart(2,'0')).join('');
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),n=>n.toString(16).padStart(2,'0')).join('');
const safePath=p=>typeof p==='string'&&p.length<240&&p.split('/').every(s=>s.length>0&&s!=='.'&&s!=='..'&&/^[A-Za-z0-9_ .@()-]+$/.test(s));
const mime=p=>({js:'text/javascript',css:'text/css',json:'application/json',svg:'image/svg+xml',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',avif:'image/avif',mp3:'audio/mpeg',mp4:'video/mp4',webm:'video/webm',ogg:'audio/ogg',wav:'audio/wav',woff:'font/woff',woff2:'font/woff2',ttf:'font/ttf',otf:'font/otf',eot:'application/vnd.ms-fontobject',txt:'text/plain',md:'text/plain'}[p.split('.').pop().toLowerCase()]||'application/octet-stream');
export async function isAdmin(env,user){return !!user&&!!await env.DB.prepare('SELECT user_id FROM admins WHERE user_id=?').bind(user.id).first();}
async function data(request,max=128*1024){if(!request.headers.get('Content-Type')?.startsWith('application/json'))fail(415,'JSON required.');const t=await request.text();if(t.length>max)fail(413,'Request too large.');try{const v=JSON.parse(t);if(!v||typeof v!=='object'||Array.isArray(v))throw Error();return v;}catch{fail(400,'Invalid JSON.');}}
const audit=(env,user,action,target)=>env.DB.prepare('INSERT INTO admin_audit(id,user_id,action,target) VALUES(?,?,?,?)').bind(uuid(),user.id,action,target);
function str(v,max,required=true){if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail(400,'Missing or invalid course details.');return v.trim();}
function quizCheck(q){if(!Array.isArray(q)||q.length!==10||q.some(x=>!x||typeof x.prompt!=='string'||!x.prompt.trim()||x.prompt.length>1500||!Array.isArray(x.options)||x.options.length<2||x.options.length>6||x.options.some(o=>typeof o!=='string'||!o.trim()||o.length>1000)||new Set(x.options).size!==x.options.length||!Number.isInteger(x.correct)||x.correct<0||x.correct>=x.options.length))fail(400,'Provide 10 questions, each with 2–6 distinct options and one correct answer.');return q.map(x=>({prompt:x.prompt.trim(),options:x.options.map(o=>o.trim()),correct:x.correct}));}
async function courseRow(env,id,includeDeleted=false){const c=await env.DB.prepare('SELECT * FROM courses WHERE id=?').bind(id).first();if(!c)fail(404,'Course not found.');if(c.deleted_at&&!includeDeleted)fail(409,'Restore this course from Trash before editing it.');return c;}
export async function activityState(env,user,course){
 const activities=(await env.DB.prepare(`SELECT p.id,p.title,a.required,EXISTS(SELECT 1 FROM activity_completions x WHERE x.user_id=? AND x.course_id=a.course_id AND x.package_id=a.package_id) completed
  FROM course_activities a JOIN activity_packages p ON p.id=a.package_id AND p.status='ready' WHERE a.course_id=? ORDER BY p.created_at,p.id`).bind(user.id,course.id).all()).results.map(a=>({...a,required:!!a.required,completed:!!a.completed}));
 const activityRequired=activities.some(a=>a.required),activityCompleted=activities.filter(a=>a.required).every(a=>a.completed);
 return {activities,activity:activities[0]?{id:activities[0].id,title:activities[0].title}:null,activityRequired,activityCompleted};
}
export async function requireActivity(env,user,course){const s=await activityState(env,user,course);if(s.activities.some(a=>a.required&&!a.completed))fail(403,'Complete all required interactive activities before taking the test.');}
async function launch(env,user,course,packageId,preview){
 const token=random();await env.DB.prepare('INSERT INTO activity_launches(token_hash,user_id,course_id,package_id,preview,expires_at) VALUES(?,?,?,?,?,unixepoch()+7200)').bind(await sha(token),user.id,course.id,packageId,preview?1:0).run();
 return json({token,playerUrl:'/api/activity-player/'+token,activityId:packageId,courseId:course.id,preview});
}
async function launchRow(env,token){if(!/^[a-f0-9]{64}$/.test(token))fail(404,'Activity not found.');const row=await env.DB.prepare('SELECT l.*,p.status FROM activity_launches l JOIN activity_packages p ON p.id=l.package_id WHERE token_hash=? AND expires_at>unixepoch() AND p.status=\'ready\'').bind(await sha(token)).first();if(!row)fail(403,'Activity session expired. Reopen the activity.');const admin=await isAdmin(env,{id:row.user_id});const allowed=admin||await env.DB.prepare('SELECT a.id FROM course_access a JOIN courses c ON c.id=? AND c.published=1 WHERE a.user_id=? AND (a.course_id=c.id OR a.course_id IS NULL) AND a.revoked_at IS NULL AND (a.expires_at IS NULL OR a.expires_at>unixepoch())').bind(row.course_id,row.user_id).first();if(!allowed)fail(403,'Activity access is no longer active.');return row;}
// These routes intentionally use a short-lived capability, never the learner's cookie.
// The player runs in an opaque-origin sandbox and cannot read LMS/admin responses.
export async function activityPublic(request,env){
 const url=new URL(request.url),m=/^\/api\/(activity-player|activity-assets)\/([a-f0-9]{64})(?:\/(.*))?$/.exec(url.pathname);if(!m)return null;
 if(!['GET','HEAD'].includes(request.method))fail(405,'Method not allowed.');
 const row=await launchRow(env,m[2]);
 if(m[1]==='activity-assets'){
  let p;try{p=decodeURIComponent(m[3]||'');}catch{fail(400,'Invalid path.');}if(!safePath(p))fail(404,'Asset not found.');
  const f=await env.DB.prepare('SELECT size FROM activity_files WHERE package_id=? AND path=? AND uploaded=1').bind(row.package_id,p).first();if(!f)fail(404,'Asset not found.');
  const object=await env.COURSE_STORAGE.get('activities/'+row.package_id+'/'+p);if(!object)fail(404,'Asset not found.');
  return new Response(request.method==='HEAD'?null:object.body,{headers:{'Content-Type':mime(p),'Content-Length':String(f.size),'Access-Control-Allow-Origin':'*','Cache-Control':'private, no-store','Content-Security-Policy':"sandbox; default-src 'none'"}});
 }
 const base=url.origin,assets=base+'/api/activity-assets/'+m[2]+'/',vendor=base+'/LMS/vendor/h5p/';
 const csp=`sandbox allow-scripts; default-src 'none'; script-src ${vendor} ${assets} ${base}/LMS/activity-player.js 'unsafe-inline' 'unsafe-eval'; style-src ${vendor} ${assets} 'unsafe-inline'; connect-src ${assets}; img-src ${assets} ${vendor} data: blob:; media-src ${assets} blob:; font-src ${vendor} ${assets} data:; frame-src about: blob:; frame-ancestors 'self'; base-uri 'none'; form-action 'none'`;
 const html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Interactive activity</title><link rel="stylesheet" href="${vendor}styles/h5p.css"><script src="${vendor}main.bundle.js" defer></script><script src="${base}/LMS/activity-player.js" defer></script></head><body data-assets="${assets}" data-vendor="${vendor}" data-activity="${row.package_id}" data-token="${m[2]}"><p id="activity-loading">Loading interactive activity…</p><div id="h5p-container"></div></body></html>`;
 return new Response(html,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':csp,'Referrer-Policy':'no-referrer'}});
}
export async function learnerActivity(request,env,user,course,action){
 const input=await data(request);
 if(action==='launch'){const s=await activityState(env,user,course),activity=input.packageId?s.activities.find(a=>a.id===input.packageId):s.activities[0];if(!activity)fail(404,'Interactive activity not found.');return launch(env,user,course,activity.id,false);}
 const row=await launchRow(env,String(input.token||''));
 if(row.user_id!==user.id||row.course_id!==course.id||row.preview)fail(403,'Activity session does not belong to this course and learner.');
 const current=await activityState(env,user,course);if(!current.activities.some(a=>a.id===row.package_id))fail(409,'This activity has changed. Reopen the lesson.');
 validateCompletion(input,row.package_id);
 await env.DB.prepare('INSERT INTO activity_completions(user_id,course_id,package_id) VALUES(?,?,?) ON CONFLICT DO NOTHING').bind(user.id,course.id,row.package_id).run();return json({completed:true});
}
function validateCompletion(input,id){if(input.activityId!==id||input.objectId!=='urn:advancedcpe:activity:'+id||!['completed','answered','passed'].includes(input.verb)||input.completed!==true)fail(400,'The complete activity must report completion, not an individual step.');}
export async function adminRoute(request,env,user){
 if(!await isAdmin(env,user))fail(403,'Administrator access required.');
 const url=new URL(request.url),p=url.pathname.slice('/api/admin'.length),post=request.method==='POST';
 if(!['GET','POST'].includes(request.method))fail(405,'Method not allowed.');
 if(p==='/notes'&&!post)return json({text:typeof __BUILD_NOTES__==='string'?__BUILD_NOTES__:'Build the site to include the private README build notes.'});
 if(p==='/learners'&&!post){const {results}=await env.DB.prepare(`SELECT u.id,u.name,u.email,u.created_at,(SELECT count(*) FROM certificates c WHERE c.user_id=u.id) certificates,(SELECT count(*) FROM quiz_attempts q WHERE q.user_id=u.id AND q.submitted_at IS NOT NULL) tests FROM users u ORDER BY u.created_at DESC LIMIT 200`).all();return json({learners:results});}
 const learner=/^\/learners\/([a-z0-9-]+)$/.exec(p);
 if(learner&&!post){const {results}=await env.DB.prepare('SELECT c.course_code,c.title,q.attempt_number,q.score,q.passed,q.submitted_at FROM quiz_attempts q JOIN courses c ON c.id=q.course_id WHERE q.user_id=? AND q.submitted_at IS NOT NULL ORDER BY q.submitted_at DESC LIMIT 300').bind(learner[1]).all();return json({results});}
 if(p==='/courses'&&!post){return json({courses:(await env.DB.prepare('SELECT id,title,course_code,category,published,asset_key,youtube_id,duration_seconds,admin_revision,deleted_at,topic_path FROM courses ORDER BY category,course_code').all()).results});}
 const trash=/^\/courses\/([a-z0-9-]+)\/(trash|restore)$/.exec(p);
 if(trash&&post){const c=await courseRow(env,trash[1],true),d=await data(request);if(d.revision!==c.admin_revision)fail(409,'This course changed. Reload before continuing.');if(d.confirmCode!==c.course_code)fail(400,'Type the course code to confirm.');const restore=trash[2]==='restore';if(restore?!c.deleted_at:!!c.deleted_at)fail(409,'Course is already in that state.');const result=await env.DB.batch([env.DB.prepare('UPDATE courses SET deleted_at=?,published=0,admin_revision=admin_revision+1 WHERE id=? AND admin_revision=?').bind(restore?null:Math.floor(Date.now()/1000),c.id,d.revision),audit(env,user,restore?'course-restore':'course-trash',c.id)]);if(!result[0].meta.changes)fail(409,'Course changed; reload.');return json({ok:true});}
 const cm=/^\/courses\/([a-z0-9-]+)$/.exec(p);
 if(cm&&!post){const c=await courseRow(env,cm[1],true);const q=await env.DB.prepare('SELECT version,questions_json FROM course_quizzes WHERE course_id=?').bind(c.id).first();const activities=(await env.DB.prepare('SELECT p.id,p.title,p.main_library,p.status,p.verified_at,a.required,CASE WHEN a.package_id=p.id THEN 1 ELSE 0 END attached,EXISTS(SELECT 1 FROM activity_completions x WHERE x.user_id=? AND x.course_id=p.course_id AND x.package_id=p.id) admin_completed FROM activity_packages p LEFT JOIN course_activities a ON a.course_id=p.course_id AND a.package_id=p.id WHERE p.course_id=? ORDER BY p.created_at DESC').bind(user.id,c.id).all()).results;return json({course:c,questions:q?JSON.parse(q.questions_json):[],quizVersion:q?.version||0,activities});}
 if((p==='/courses'||cm)&&post){
  const d=await data(request),existing=cm?await courseRow(env,cm[1]):null,id=existing?.id||'course-'+uuid();
  const title=str(d.title,200),description=str(d.description,2000),category=str(d.category,100),code=str(d.course_code,30),level=str(d.level||'Foundational',50);
  if(!/^[A-Z][A-Z0-9-]{2,29}$/.test(code))fail(400,'Use an uppercase catalog code, such as NFP-117.');
  if(await env.DB.prepare('SELECT id FROM courses WHERE course_code=? AND id<>?').bind(code,id).first())fail(409,'That course code is already in use.');
  if(existing&&d.revision!==existing.admin_revision)fail(409,'This course changed in another window. Reload before saving.');
  const questions=d.questions?.length?quizCheck(d.questions):null,published=d.published===true?1:0;
  const existingQuiz=existing&&!questions?await env.DB.prepare('SELECT course_id FROM course_quizzes WHERE course_id=? AND published=1').bind(id).first():null;
  if(published&&!existing?.topic_path&&((!existing?.asset_key&&!existing?.youtube_id)||existing.duration_seconds<=0||(!questions&&!existingQuiz)))fail(400,'Upload a video and provide all ten test questions before publishing.');
  const statements=[];
  if(existing)statements.push(env.DB.prepare('UPDATE courses SET title=?,description=?,category=?,course_code=?,level=?,published=?,admin_revision=admin_revision+1 WHERE id=? AND admin_revision=?').bind(title,description,category,code,level,published,id,d.revision));
  else statements.push(env.DB.prepare('INSERT INTO courses(id,title,description,category,course_code,level,hours,published,duration_seconds) VALUES(?,?,?,?,?,?,0,0,0)').bind(id,title,description,category,code,level));
  if(questions)statements.push(env.DB.prepare('INSERT INTO course_quizzes(course_id,version,questions_json,published) SELECT ?,1,?,1 WHERE changes()=1 ON CONFLICT(course_id) DO UPDATE SET version=version+1,questions_json=excluded.questions_json,published=1').bind(id,JSON.stringify(questions)));
  statements.push(audit(env,user,existing?'course-save':'course-create',id));const results=await env.DB.batch(statements);if(!results[0].meta.changes)fail(409,'Course changed; reload.');return json({id});
 }
 const yt=/^\/courses\/([a-z0-9-]+)\/youtube$/.exec(p);
 if(yt&&post){const c=await courseRow(env,yt[1]),d=await data(request),id=youtubeId(d.url);checkVideoChange(c,d,d.duration);const batch=videoChangeStatements(env,user,c,{youtubeId:id,duration:d.duration},d.progressMode);const r=await env.DB.batch([...batch,audit(env,user,'video-youtube',c.id)]);if(!r[batch.length-1].meta.changes)fail(409,'Course changed; reload.');return json({ok:true,youtubeId:id});}
 const vm=/^\/courses\/([a-z0-9-]+)\/video-upload$/.exec(p);
 if(vm&&post){const c=await courseRow(env,vm[1]),d=await data(request);checkVideoChange(c,d,d.duration);if(!Number.isInteger(d.size)||d.size<12||d.size>2*1024**3||!Number.isFinite(d.duration)||d.duration<=0||d.duration>24*3600)fail(400,'Choose an MP4 up to 2 GB with a valid duration.');const id=uuid(),key='courses/'+c.id+'/'+id+'.mp4',upload=await env.COURSE_STORAGE.createMultipartUpload(key,{httpMetadata:{contentType:'video/mp4'}});await env.DB.batch([env.DB.prepare('INSERT INTO media_uploads(id,course_id,user_id,r2_key,upload_id,size,duration,expected_revision,progress_mode) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,c.id,user.id,key,upload.uploadId,d.size,d.duration,c.admin_revision,d.progressMode),audit(env,user,'video-upload-start',id)]);return json({id,partSize:8*1024**2});}
 const up=/^\/video-uploads\/([a-f0-9-]+)\/(part|complete|abort)$/.exec(p);
 if(up&&post){const u=await env.DB.prepare('SELECT * FROM media_uploads WHERE id=? AND user_id=?').bind(up[1],user.id).first();if(!u)fail(404,'Upload not found.');if(u.status==='complete'&&up[2]==='complete')return json({ok:true});if(u.status!=='uploading')fail(409,'Upload is no longer active.');const upload=env.COURSE_STORAGE.resumeMultipartUpload(u.r2_key,u.upload_id);
  if(up[2]==='part'){const n=Number(url.searchParams.get('number')),parts=Math.ceil(u.size/(8*1024**2)),size=n===parts?u.size-(n-1)*8*1024**2:8*1024**2;if(!Number.isInteger(n)||n<1||n>parts||Number(request.headers.get('Content-Length'))!==size)fail(400,'Invalid upload part.');const bytes=await request.arrayBuffer();if(bytes.byteLength!==size)fail(400,'Invalid part size.');if(n===1&&new TextDecoder().decode(bytes.slice(4,8))!=='ftyp')fail(400,'The video must be an MP4 file.');const part=await upload.uploadPart(n,bytes);await env.DB.prepare('INSERT INTO media_parts(upload_id,part_number,etag,size) VALUES(?,?,?,?) ON CONFLICT(upload_id,part_number) DO UPDATE SET etag=excluded.etag,size=excluded.size').bind(u.id,n,part.etag,size).run();return json({ok:true});}
  if(up[2]==='abort'){await upload.abort();await env.DB.prepare("UPDATE media_uploads SET status='aborted' WHERE id=?").bind(u.id).run();return json({ok:true});}
  const parts=(await env.DB.prepare('SELECT part_number,etag,size FROM media_parts WHERE upload_id=? ORDER BY part_number').bind(u.id).all()).results;if(parts.length!==Math.ceil(u.size/(8*1024**2))||parts.reduce((s,x)=>s+x.size,0)!==u.size)fail(400,'Upload is incomplete.');
  const already=await env.COURSE_STORAGE.head(u.r2_key);if(!already)await upload.complete(parts.map(x=>({partNumber:x.part_number,etag:x.etag})));
  const c=await courseRow(env,u.course_id);checkVideoChange(c,{revision:u.expected_revision,progressMode:u.progress_mode},u.duration);const batch=videoChangeStatements(env,user,c,{assetKey:u.r2_key,duration:u.duration},u.progress_mode);batch.push(env.DB.prepare("UPDATE media_uploads SET status='complete' WHERE id=? AND EXISTS(SELECT 1 FROM courses WHERE id=? AND asset_key=?)").bind(u.id,c.id,u.r2_key),audit(env,user,'video-upload-complete',u.course_id));const results=await env.DB.batch(batch);if(!results[3].meta.changes)fail(409,'Course changed; reload before uploading again.');return json({ok:true});
 }
 const am=/^\/courses\/([a-z0-9-]+)\/activities$/.exec(p);
 if(am&&post){const c=await courseRow(env,am[1]),d=await data(request,512*1024);if(c.topic_path)fail(400,'Attach activities to video courses, not reading guides.');const title=str(d.title,200),files=d.files;if(!Array.isArray(files)||!files.length||files.length>2000)fail(400,'The package must contain 1–2000 files.');let total=0;const names=new Set();for(const f of files){if(!safePath(f.path)||names.has(f.path)||!Number.isInteger(f.size)||f.size<0||f.size>16*1024**2||!/^[a-f0-9]{64}$/.test(f.sha256))fail(400,'Invalid package file. Maximum individual file size is 16 MB.');names.add(f.path);total+=f.size;}if(total>128*1024**2||!names.has('h5p.json')||!names.has('content/content.json'))fail(400,'Use a complete .h5p export with libraries, up to 128 MB expanded.');const id=uuid();await env.DB.prepare('INSERT INTO activity_packages(id,course_id,user_id,title) VALUES(?,?,?,?)').bind(id,c.id,user.id,title).run();for(let i=0;i<files.length;i+=50)await env.DB.batch(files.slice(i,i+50).map(f=>env.DB.prepare('INSERT INTO activity_files(package_id,path,size,sha256) VALUES(?,?,?,?)').bind(id,f.path,f.size,f.sha256)));await audit(env,user,'activity-upload-start',id).run();return json({id});}
 const pkg=/^\/activities\/([a-f0-9-]+)\/(file|finalize|attach|launch|verify)$/.exec(p);
 if(pkg&&post){const pack=await env.DB.prepare('SELECT * FROM activity_packages WHERE id=?').bind(pkg[1]).first();if(!pack)fail(404,'Package not found.');const c=await courseRow(env,pack.course_id);
  if(pkg[2]==='file'){if(pack.status!=='uploading'||pack.user_id!==user.id)fail(409,'Package is not writable.');const path=url.searchParams.get('path');if(!safePath(path))fail(400,'Invalid package path.');const f=await env.DB.prepare('SELECT * FROM activity_files WHERE package_id=? AND path=?').bind(pack.id,path).first();if(!f||Number(request.headers.get('Content-Length'))!==f.size)fail(400,'Invalid package file length.');const bytes=await request.arrayBuffer();if(bytes.byteLength!==f.size||await sha(bytes)!==f.sha256)fail(400,'Package file checksum mismatch.');await env.COURSE_STORAGE.put('activities/'+pack.id+'/'+path,bytes,{httpMetadata:{contentType:mime(path)}});await env.DB.prepare('UPDATE activity_files SET uploaded=1 WHERE package_id=? AND path=?').bind(pack.id,path).run();return json({ok:true});}
  if(pkg[2]==='finalize'){if(pack.status==='ready')return json({ok:true});if(pack.user_id!==user.id)fail(403,'Only the uploader can finalize this package.');const missing=await env.DB.prepare('SELECT count(*) n FROM activity_files WHERE package_id=? AND uploaded=0').bind(pack.id).first();if(missing.n)fail(400,'Package upload is incomplete.');const main=await validatePackage(env,pack.id);await env.DB.batch([env.DB.prepare("UPDATE activity_packages SET status='ready',main_library=? WHERE id=?").bind(main,pack.id),audit(env,user,'activity-upload-ready',pack.id)]);return json({ok:true});}
  if(pack.status!=='ready')fail(409,'Finish uploading first.');
  if(pkg[2]==='launch')return launch(env,user,c,pack.id,true);
  if(pkg[2]==='verify'){const d=await data(request),l=await launchRow(env,String(d.token||''));if(!l.preview||l.user_id!==user.id||l.package_id!==pack.id)fail(403,'Invalid preview session.');validateCompletion(d,pack.id);await env.DB.batch([env.DB.prepare('UPDATE activity_packages SET verified_at=unixepoch() WHERE id=?').bind(pack.id),audit(env,user,'activity-preview-verified',pack.id)]);return json({verified:true});}
  const d=await data(request);if(d.required===true&&!pack.verified_at)fail(400,'Complete the preview first to verify completion tracking before making this activity required.');await env.DB.batch([env.DB.prepare('INSERT INTO course_activities(course_id,package_id,required) VALUES(?,?,?) ON CONFLICT(course_id,package_id) DO UPDATE SET required=excluded.required').bind(c.id,pack.id,d.required===true?1:0),audit(env,user,'activity-attach',pack.id)]);return json({ok:true});
 }
 const mark=/^\/courses\/([a-z0-9-]+)\/activities\/([a-f0-9-]+)\/completion$/.exec(p);
 if(mark&&post){const c=await courseRow(env,mark[1]),d=await data(request);if(typeof d.completed!=='boolean')fail(400,'Choose whether the activity is complete.');const attached=await env.DB.prepare('SELECT 1 AS linked FROM course_activities WHERE course_id=? AND package_id=?').bind(c.id,mark[2]).first();if(!attached)fail(404,'This activity is not attached to the course.');if(d.completed)await env.DB.prepare('INSERT INTO activity_completions(user_id,course_id,package_id) VALUES(?,?,?) ON CONFLICT(user_id,course_id,package_id) DO NOTHING').bind(user.id,c.id,mark[2]).run();else await env.DB.prepare('DELETE FROM activity_completions WHERE user_id=? AND course_id=? AND package_id=?').bind(user.id,c.id,mark[2]).run();await audit(env,user,d.completed?'admin-activity-complete':'admin-activity-uncomplete',c.id+':'+mark[2]).run();return json({completed:d.completed});}
 fail(404,'Admin endpoint not found.');
}
async function validatePackage(env,id){
 const files=(await env.DB.prepare('SELECT path FROM activity_files WHERE package_id=? AND uploaded=1').bind(id).all()).results;const names=new Set(files.map(x=>x.path));
 async function read(path){if(!names.has(path))fail(400,'Missing package dependency: '+path);const o=await env.COURSE_STORAGE.get('activities/'+id+'/'+path);if(!o||o.size>1024*1024)fail(400,'Missing or oversized package metadata.');try{return JSON.parse(await o.text());}catch{fail(400,'Invalid JSON in '+path);}}
 const h5p=await read('h5p.json');await read('content/content.json');if(typeof h5p.mainLibrary!=='string'||!/^H5P\.[A-Za-z0-9]+$/.test(h5p.mainLibrary)||!Array.isArray(h5p.preloadedDependencies))fail(400,'Invalid H5P manifest.');
 const seen=new Set();async function dependency(d){if(!d||!/^[A-Za-z0-9.]+$/.test(d.machineName)||!/^\d{1,3}$/.test(String(d.majorVersion))||!/^\d{1,3}$/.test(String(d.minorVersion)))fail(400,'Invalid H5P library reference.');const dir=`${d.machineName}-${d.majorVersion}.${d.minorVersion}`;if(seen.has(dir))return;seen.add(dir);if(seen.size>100)fail(400,'Too many H5P libraries.');const lib=await read(dir+'/library.json');if(lib.machineName!==d.machineName||Number(lib.majorVersion)!==Number(d.majorVersion)||Number(lib.minorVersion)!==Number(d.minorVersion))fail(400,'H5P library version mismatch.');for(const asset of [...(lib.preloadedJs||[]),...(lib.preloadedCss||[])])if(!safePath(asset.path)||!names.has(dir+'/'+asset.path))fail(400,'Missing H5P library asset. Export with libraries included.');for(const child of [...(lib.preloadedDependencies||[]),...(lib.dynamicDependencies||[])])await dependency(child);}
 for(const d of h5p.preloadedDependencies)await dependency(d);
 if(!h5p.preloadedDependencies.some(d=>d.machineName===h5p.mainLibrary))fail(400,'Missing main H5P library.');return h5p.mainLibrary;
}
